import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./v1/auth";
import dashboardRouter from "./v1/dashboard";
import examCategoriesRouter from "./v1/exam-categories";
import examsRouter from "./v1/exams";
import subjectsRouter from "./v1/subjects";
import questionsRouter from "./v1/questions";
import sessionsRouter from "./v1/sessions";
import resultsRouter from "./v1/results";
import leaderboardRouter from "./v1/leaderboard";
import notificationsRouter from "./v1/notifications";
import notesRouter from "./v1/notes";
import usersRouter from "./v1/users";
import bookmarksRouter from "./v1/bookmarks";
import wrongAnswersRouter from "./v1/wrong-answers";
import settingsRouter from "./v1/settings";
import violationsRouter from "./v1/violations";
import achievementsRouter from "./v1/achievements";
import currentAffairsRouter from "./v1/current-affairs";
import superAdminRouter from "./v1/super-admin";
import uploadRouter from "./v1/upload";
import filesRouter from "./v1/files";
import collectionsRouter from "./v1/collections";
import repositoryRouter from "./v1/repository";
import practiceRouter from "./v1/practice";
import analyticsRouter from "./v1/analytics";
import adaptiveRouter from "./v1/adaptive";
import gamificationRouter from "./v1/gamification";
import missionsRouter from "./v1/missions";
import goalsRouter from "./v1/goals";
import studyTasksRouter from "./v1/study-tasks";
import performanceTimelineRouter from "./v1/performance-timeline";
import exportsRouter from "./v1/exports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(examCategoriesRouter);
router.use(examsRouter);
router.use(subjectsRouter);
router.use(questionsRouter);
router.use(sessionsRouter);
router.use(violationsRouter);
router.use(resultsRouter);
router.use(leaderboardRouter);
router.use(notificationsRouter);
router.use(notesRouter);
router.use(usersRouter);
router.use(bookmarksRouter);
router.use(wrongAnswersRouter);
router.use(settingsRouter);
router.use(achievementsRouter);
router.use(currentAffairsRouter);
router.use(superAdminRouter);
router.use(uploadRouter);
router.use(filesRouter);
router.use(collectionsRouter);
router.use(repositoryRouter);
router.use(practiceRouter);
router.use(analyticsRouter);
router.use(adaptiveRouter);
router.use(gamificationRouter);
router.use(missionsRouter);
router.use(goalsRouter);
router.use(studyTasksRouter);
router.use(performanceTimelineRouter);
router.use(exportsRouter);


export default router;
